flock-geekten/flock

api/Gemfile.lock
view/flock_view/components/Form.vue
view/flock_view/nuxt.config.js
view/flock_view/package-lock.json
view/flock_view/package.json
view/flock_view/pages/articles/_id.vue
view/flock_view/pages/index.vue
view/flock_view/pages/new.vue

resolve #5
resolve #8 
タイトルの通り

記事の詳細ページの追加，編集/削除機能の追加

---

view/flock_view/components/Article.vue
view/flock_view/components/Header.vue
view/flock_view/components/UserInfo.vue
view/flock_view/layouts/default.vue
view/flock_view/pages/articles/_id.vue
view/flock_view/pages/index.vue
view/flock_view/pages/login.vue
view/flock_view/store/user.js

[add] ユーザー情報の表示(#20)

---

view/flock_view/components/UserInfo.vue
view/flock_view/pages/mypage.vue
view/flock_view/pages/users/_id.vue

[add] mypage userpage(#21)(#22)

---

api/apis/app/controllers/api/v1/posts_api_controller.rb
api/apis/app/controllers/comments_controller.rb
api/apis/app/models/comment.rb
api/apis/app/models/post.rb
api/apis/app/models/user.rb
api/apis/config/routes.rb
api/apis/db/migrate/20210830121711_create_comments.rb
api/apis/db/schema.rb
view/flock_view/components/Comments.vue
view/flock_view/pages/articles/_id.vue

[add] コメント機能追加(#19)

---

api/apis/app/controllers/api/v1/users_controller.rb
api/apis/app/controllers/likes_controller.rb
api/apis/app/controllers/users_controller.rb
api/apis/app/models/like.rb
api/apis/app/models/post.rb
api/apis/app/models/user.rb
api/apis/config/routes.rb
api/apis/db/migrate/20210830150825_create_likes.rb
api/apis/db/schema.rb
view/flock_view/components/Comments.vue
view/flock_view/pages/articles/_id.vue
view/flock_view/pages/login.vue
view/flock_view/pages/mypage.vue
view/flock_view/pages/signup.vue
view/flock_view/pages/users/_id.vue

[mod] いいね機能の追加(#26)

---

api/apis/app/controllers/api/v1/users_controller.rb
api/apis/app/controllers/likes_controller.rb
api/apis/app/controllers/relationships_controller.rb
api/apis/app/controllers/users_controller.rb
api/apis/app/models/relationship.rb
api/apis/app/models/user.rb
api/apis/config/routes.rb
api/apis/db/migrate/20210831035445_create_relationships.rb
api/apis/db/schema.rb
view/flock_view/components/Comments.vue
view/flock_view/pages/login.vue
view/flock_view/pages/mypage.vue
view/flock_view/pages/signup.vue
view/flock_view/pages/users/_id.vue

[add] フォロー機能の作成 バグ修正 (#30)(#31)

---

api/apis/Gemfile
api/apis/Gemfile.lock
api/apis/app/controllers/hangouts_controller.rb
api/apis/app/controllers/posts_controller.rb
api/apis/app/controllers/users_controller.rb
api/apis/app/models/hangout.rb
api/apis/config/routes.rb
api/apis/db/fixtures/hangouts.rb
api/apis/db/migrate/20210904122353_create_hangouts.rb
api/apis/db/migrate/20210904124154_add_age_to_users.rb
api/apis/db/schema.rb
docker-compose.yml
view/flock_view/components/Header.vue
view/flock_view/pages/articles/_id.vue
view/flock_view/pages/friends/index.vue
view/flock_view/pages/hangouts/recommend.vue
view/flock_view/pages/signup.vue

[add] あそびレコメンドと友達レコメンドのページだけ作成(#38)

---

api/apis/app/controllers/api/v1/posts_api_controller.rb
api/apis/app/controllers/api/v1/users_controller.rb
api/apis/app/controllers/likes_controller.rb
api/apis/app/controllers/users_controller.rb
api/apis/db/migrate/20210905074147_add_profile_to_users.rb
api/apis/db/schema.rb
view/flock_view/components/Header.vue
view/flock_view/components/UserEdit.vue
view/flock_view/pages/articles/_id.vue
view/flock_view/pages/index.vue
view/flock_view/pages/logout.vue
view/flock_view/pages/mypage/index.vue
view/flock_view/pages/users/_id.vue

[add] UIをいい感じに(#41)

---

view/flock_view/components/Header.vue
view/flock_view/layouts/default.vue
view/flock_view/pages/index.vue

[mod] トップページのviewを整える(#52)

---

api/apis/app/controllers/api/v1/tags_api_controller.rb
api/apis/config/routes.rb
view/flock_view/components/Tags.vue
view/flock_view/nuxt.config.js
view/flock_view/pages/tags/_id.vue

[add] タグに紐づいた記事を取得, ページ遷移のときに一番上にスクロール(#55)(#60)

---

view/flock_view/components/Comments.vue
view/flock_view/components/Form.vue
view/flock_view/components/Header.vue
view/flock_view/components/Menu.vue
view/flock_view/components/Summary.vue
view/flock_view/components/UserEdit.vue
view/flock_view/pages/articles/_id.vue
view/flock_view/pages/articles/confirm.vue
view/flock_view/pages/articles/new.vue
view/flock_view/pages/hangouts/choose.vue
view/flock_view/pages/index.vue
view/flock_view/pages/logout.vue
view/flock_view/pages/mypage/index.vue
view/flock_view/pages/signup.vue
view/flock_view/pages/tags/_id.vue
view/flock_view/pages/users/_id.vue

[mod] rippleをfalseに(#63)

---

api/apis/app/controllers/api/v1/results_api_controller.rb
api/apis/app/controllers/api/v1/scores_api_controller.rb
api/apis/app/controllers/hangouts_controller.rb
api/apis/app/models/hangout.rb
api/apis/app/models/user.rb
api/apis/app/models/user_hangout_fun.rb
api/apis/app/models/user_hangout_result.rb
api/apis/config/routes.rb
api/apis/db/fixtures/user.rb
api/apis/db/migrate/20210909074720_create_user_hangout_funs.rb
api/apis/db/migrate/20210909074804_create_user_hangout_results.rb
api/apis/db/schema.rb
view/flock_view/components/Summary.vue
view/flock_view/pages/hangouts/choose.vue

[add] あそびの選択画面を真面目に作る(#67)

---

api/apis/app/controllers/api/v1/users_controller.rb
api/apis/app/controllers/participations_controller.rb
api/apis/app/controllers/plan_comments_controller.rb
api/apis/app/controllers/plans_controller.rb
api/apis/app/controllers/users_controller.rb
api/apis/app/models/participation.rb
api/apis/app/models/plan.rb
api/apis/app/models/plan_comment.rb
api/apis/app/models/user.rb
api/apis/config/routes.rb
api/apis/db/fixtures/user.rb
api/apis/db/migrate/20210909115638_create_plans.rb
api/apis/db/migrate/20210909115714_create_participations.rb
api/apis/db/migrate/20210909115757_create_plan_comments.rb
api/apis/db/schema.rb
view/flock_view/components/Header.vue
view/flock_view/components/PlanComments.vue
view/flock_view/components/Plans.vue
view/flock_view/layouts/default.vue
view/flock_view/pages/index.vue
view/flock_view/pages/mypage/index.vue
view/flock_view/pages/plans/_id.vue
view/flock_view/pages/plans/new.vue
view/flock_view/pages/users/_id.vue

[mod] 予定計画機能(#69)

---

api/apis/app/controllers/api/v1/friends_api_controller.rb
api/apis/app/controllers/users_controller.rb
api/apis/db/fixtures/user.rb
view/flock_view/pages/admin.vue
view/flock_view/pages/friends/index.vue
view/flock_view/pages/hangouts/ready.vue

[mod] あそびを追加しても友達レコメンドができるように修正(#81)

---

view/flock_view/layouts/default.vue
view/flock_view/pages/hangouts/recommend.vue

[mod] あそびのレコメンド時に評価ができるように変更(#85)

---

ml_models/recommendation_models/fun_recommendation.py
view/flock_view/pages/hangouts/recommend.vue

[fix] あそびの評価が更新されない問題を解決(#87)

---

view/flock_view/pages/admin.vue

[mod] あそびを追加できるように（カラム変更版）(#91)

---

view/flock_view/components/Comments.vue
view/flock_view/components/PlanComments.vue
view/flock_view/components/Summary.vue
view/flock_view/pages/articles/_id.vue
view/flock_view/pages/articles/edit/_id.vue
view/flock_view/pages/articles/new.vue

[mod] 編集のバグを解消，コメントは空文字での投稿はできないようにする(#98)

---

ml_models/extractive_summarization/data_cleaning.py
ml_models/keyphrase_extraction/data_cleaning.py
ml_models/requirements.txt

要約とキーフレーズの前処理に絵文字除去を追加

---

api/apis/app/controllers/plans_controller.rb
view/flock_view/components/Comments.vue
view/flock_view/components/PlanComments.vue
view/flock_view/components/Plans.vue
view/flock_view/components/Summary.vue
view/flock_view/components/Tags.vue
view/flock_view/components/UserInfo.vue
view/flock_view/pages/articles/_id.vue
view/flock_view/pages/articles/confirm.vue
view/flock_view/pages/articles/edit/_id.vue
view/flock_view/pages/articles/new.vue
view/flock_view/pages/hangouts/choose.vue
view/flock_view/pages/hangouts/first.vue
view/flock_view/pages/hangouts/ready.vue
view/flock_view/pages/hangouts/recommend.vue
view/flock_view/pages/logout.vue
view/flock_view/pages/mypage/index.vue
view/flock_view/pages/plans/_id.vue
view/flock_view/pages/users/_id.vue

[fix]あそびの計画で参加者数やコメント数を見れるように，改行されないバグ修正(#99)

---

view/flock_view/pages/index.vue

[mod] 投稿の更新(#108)

---

view/flock_view/components/ArticleCard.vue
view/flock_view/components/TopArticles.vue
view/flock_view/pages/tags/_id.vue

[mod] 投稿のカードをコンポーネント化

---

view/flock_view/components/Summary.vue
view/flock_view/pages/articles/new.vue
view/flock_view/pages/plans/new.vue

[mod] 空行投稿をできないようにする (#117)

---

api/apis/app/controllers/api/v1/users_controller.rb
view/flock_view/pages/login.vue
view/flock_view/pages/logout.vue

[add] Googleログイン機能の追加

---

api/apis/app/controllers/api/v1/posts_api_controller.rb
api/apis/app/controllers/api/v1/users_controller.rb
api/apis/app/controllers/posts_controller.rb
api/apis/config/routes.rb
api/apis/db/migrate/20210830025021_add_column_posts.rb
api/apis/db/schema.rb
view/flock_view/components/ArticleCard.vue
view/flock_view/components/ArticleShow.vue
view/flock_view/components/ArticleShowMobile.vue
view/flock_view/layouts/default.vue
view/flock_view/pages/articles/new.vue
view/flock_view/pages/plans/_id.vue
view/flock_view/pages/plans/new.vue

あそびの記事から計画に飛ばす

---

view/flock_view/components/Header.vue
view/flock_view/pages/login.vue
view/flock_view/store/user.js

[mod] googleログインのときは画像がでるようにする(#126)
